meta_product_name: "APERO BOULOT"
meta_title: "APERO BOULOT - C'est bon, c'est frais et c'est au bureau"
meta_description: "Entourée de producteurs issus de la filière agricole française l’équipe d’APERO BOULOT s’engage à vous faire redécouvrir les vraies saveurs des aliments lors d’évènements organisés en entreprise."
meta_image: "met-img.png"                           # Une image dans votre dossier app/assets/images/
twitter_account: "@Aperoboulot"
