meta_product_name: "APERO BOULOT"
meta_title: "APERO BOULOT - C'est bon, c'est frais et c'est au boulot !"
meta_description: "Apero Boulot est un traiteur qui propose un service de livraison et d'installation pour tous les événements d'entreprise à Paris"
meta_image: "met-img.png"                           # Une image dans votre dossier app/assets/images/
twitter_account: "@Aperoboulot"
